Added error check for DNS record update to update-Cloudflare-dnsRecord

diff --git a/actions/update-Cloudflare-dnsRecord/action.yml b/actions/update-Cloudflare-dnsRecord/action.yml
--- a/actions/update-Cloudflare-dnsRecord/action.yml
+++ b/actions/update-Cloudflare-dnsRecord/action.yml
@@ -71,5 +71,12 @@ runs:
           -H "Authorization: Bearer ${{ inputs.CF_API_TOKEN }}" \
           -H "Content-Type: application/vnd.api+json" \
           "https://api.cloudflare.com/client/v4/zones/${{ inputs.CF_ZONE_ID }}/dns_records?name=${{ inputs.CF_RECORD_NAME }}")
+
         echo "DNS Update Response: "
         echo "$RESULT" | jq .
+
+        if [[ $(echo "$RESULT" | jq -r '.success') != "true" ]]; then
+          echo "DNS Update failed. Exiting."
+          exit 1
+        fi
+
