Updated buildPushImage workflow to allow arch specific builds

diff --git a/.github/workflows/buildPushImage.yaml b/.github/workflows/buildPushImage.yaml
--- a/.github/workflows/buildPushImage.yaml
+++ b/.github/workflows/buildPushImage.yaml
@@ -69,16 +69,34 @@ on:
 
 jobs:
 
-  ## PUBLIC ##
+  set-matrix:
+    runs-on: ubuntu-latest
+    outputs:
+      matrix: ${{ steps.set.outputs.matrix }}
+    steps:
+      - id: set
+        run: |
+          case "${{ inputs.ARCHITECTURE }}" in
+            mixed)
+              echo 'matrix=["amd64","arm64"]' >> $GITHUB_OUTPUT
+              ;;
+            amd64)
+              echo 'matrix=["amd64"]' >> $GITHUB_OUTPUT
+              ;;
+            arm64)
+              echo 'matrix=["arm64"]' >> $GITHUB_OUTPUT
+              ;;
+            *)
+              echo "Invalid ARCHITECTURE input"
+              exit 1
+              ;;
+          esac
 
   build-image-push-public:
+    needs: set-matrix
     strategy:
       matrix:
-        platform: ${{ fromJson(
-          inputs.ARCHITECTURE == 'mixed' && '["amd64", "arm64"]' ||
-          inputs.ARCHITECTURE == 'amd64' && '["amd64"]' ||
-          '["arm64"]'
-        ) }}
+        platform: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
         include:
           - platform: amd64
             runner: gha-runner-scale-set-amd64
@@ -95,14 +113,13 @@ jobs:
           REGISTRY: ${{ inputs.REGISTRY_PRIVATE_PULL }}
           REGISTRY_USER: ${{ secrets.REGISTRY_PRIVATE_USER }}
           REGISTRY_PASSWD: "${{ secrets.REGISTRY_PRIVATE_PASSWD }}"
-      - name: Login to public # to push
+      - name: Login to public
         uses: docker/login-action@v3
         with:
           registry: ${{ inputs.REGISTRY_PUBLIC }}
           username: ${{ secrets.REGISTRY_PUBLIC_USER }}
           password: ${{ secrets.REGISTRY_PUBLIC_PASSWD }}
       - name: Build and push to public
-        id: build
         uses: docker/build-push-action@v6
         with:
           context: ${{ inputs.CONTEXT }}
@@ -118,8 +135,8 @@ jobs:
 
   build-merge-public:
     runs-on: gha-runner-scale-set-arm64
-    if: ${{ inputs.ARCHITECTURE == 'mixed' && inputs.PUSH_TO_PUBLIC == true }}
     needs: build-image-push-public
+    if: ${{ inputs.ARCHITECTURE == 'mixed' && inputs.PUSH_TO_PUBLIC == true }}
     steps:
       - name: Set up Docker Buildx
         uses: v6Org01/.github/actions/setup-buildx-privateRegistry@main
@@ -127,7 +144,7 @@ jobs:
           REGISTRY: ${{ inputs.REGISTRY_PRIVATE_PULL }}
           REGISTRY_USER: ${{ secrets.REGISTRY_PRIVATE_USER }}
           REGISTRY_PASSWD: "${{ secrets.REGISTRY_PRIVATE_PASSWD }}"
-      - name: Login to public registry
+      - name: Login to public
         uses: docker/login-action@v3
         with:
           registry: ${{ inputs.REGISTRY_PUBLIC }}
@@ -142,16 +159,11 @@ jobs:
         run: |
           docker buildx imagetools inspect "${{ inputs.REGISTRY_PUBLIC }}/${{ inputs.OWNER }}/arc-${{ inputs.APPLICATION }}:${{ inputs.VERSION }}"
 
-  ## PRIVATE ##
-
   build-image-push-private:
+    needs: set-matrix
     strategy:
       matrix:
-        platform: ${{ fromJson(
-          inputs.ARCHITECTURE == 'mixed' && '["amd64", "arm64"]' ||
-          inputs.ARCHITECTURE == 'amd64' && '["amd64"]' ||
-          '["arm64"]'
-        ) }}
+        platform: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
         include:
           - platform: amd64
             runner: gha-runner-scale-set-amd64
@@ -168,14 +180,13 @@ jobs:
           REGISTRY: ${{ inputs.REGISTRY_PRIVATE_PULL }}
           REGISTRY_USER: ${{ secrets.REGISTRY_PRIVATE_USER }}
           REGISTRY_PASSWD: "${{ secrets.REGISTRY_PRIVATE_PASSWD }}"
-      - name: Login to private # to push
+      - name: Login to private
         uses: docker/login-action@v3
         with:
           registry: ${{ inputs.REGISTRY_PRIVATE }}
           username: ${{ secrets.REGISTRY_PRIVATE_USER }}
           password: "${{ secrets.REGISTRY_PRIVATE_PASSWD }}"
       - name: Build and push to private
-        id: build
         uses: docker/build-push-action@v6
         with:
           context: ${{ inputs.CONTEXT }}
@@ -191,8 +202,8 @@ jobs:
 
   build-merge-private:
     runs-on: gha-runner-scale-set-arm64
-    if: ${{ inputs.ARCHITECTURE == 'mixed' && inputs.PUSH_TO_PRIVATE == true }}
     needs: build-image-push-private
+    if: ${{ inputs.ARCHITECTURE == 'mixed' && inputs.PUSH_TO_PRIVATE == true }}
     steps:
       - name: Set up Docker Buildx
         uses: v6Org01/.github/actions/setup-buildx-privateRegistry@main
@@ -200,7 +211,7 @@ jobs:
           REGISTRY: ${{ inputs.REGISTRY_PRIVATE_PULL }}
           REGISTRY_USER: ${{ secrets.REGISTRY_PRIVATE_USER }}
           REGISTRY_PASSWD: "${{ secrets.REGISTRY_PRIVATE_PASSWD }}"
-      - name: Login to private # to push
+      - name: Login to private
         uses: docker/login-action@v3
         with:
           registry: ${{ inputs.REGISTRY_PRIVATE }}
