Updated buildPushImage workflow to allow arch specific builds

diff --git a/.github/workflows/buildPushImage.yaml b/.github/workflows/buildPushImage.yaml
--- a/.github/workflows/buildPushImage.yaml
+++ b/.github/workflows/buildPushImage.yaml
@@ -72,26 +72,31 @@ jobs:
   set-platform:
     runs-on: gha-runner-scale-set-arm64
     outputs:
-      platforms: ${{ steps.set-platform.outputs.platforms }}
+      platforms: ${{ steps.set.outputs.platforms }}
     steps:
-      - id: set-platform
+      - id: set
         run: |
-          if [ "${{ inputs.ARCHITECTURE }}" == "mixed" ]; then
-            echo "platforms=['amd64', 'arm64']" >> $GITHUB_ENV
-          elif [ "${{ inputs.ARCHITECTURE }}" == "amd64" ]; then
-            echo "platforms=['amd64']" >> $GITHUB_ENV
-          elif [ "${{ inputs.ARCHITECTURE }}" == "arm64" ]; then
-            echo "platforms=['arm64']" >> $GITHUB_ENV
-          else
-            echo "Invalid ARCHITECTURE value: ${{ inputs.ARCHITECTURE }}" >&2
-            exit 1
-          fi
+          case "${{ inputs.ARCHITECTURE }}" in
+            mixed)
+              echo 'platforms=["amd64","arm64"]' >> $GITHUB_OUTPUT
+              ;;
+            amd64)
+              echo 'platforms=["amd64"]' >> $GITHUB_OUTPUT
+              ;;
+            arm64)
+              echo 'platforms=["arm64"]' >> $GITHUB_OUTPUT
+              ;;
+            *)
+              echo "Invalid ARCHITECTURE: ${{ inputs.ARCHITECTURE }}"
+              exit 1
+              ;;
+          esac
 
   build-image-push-public:
     needs: set-platform
     strategy:
       matrix:
-        platform: ${{ fromJson(env.platforms) }}
+        platform: ${{ fromJson(needs.set-platform.outputs.platforms) }}
         include:
           - platform: amd64
             runner: gha-runner-scale-set-amd64
@@ -158,7 +163,7 @@ jobs:
     needs: set-platform
     strategy:
       matrix:
-        platform: ${{ fromJson(env.platforms) }}
+        platform: ${{ fromJson(needs.set-platform.outputs.platforms) }}
         include:
           - platform: amd64
             runner: gha-runner-scale-set-amd64
